### ISSUE TITLE
Requires python 3 but there is python 2.7 badge

### ISSUE THREAD

**Issue by technic** [johann-petrak/licenseheaders#18]
Hi, 
Is python3 really required? There is a python 2.7 badge but sources tell different.

**Comment by johann-petrak** [comment]
Yes, the presence of that  badge is a bug.

**Comment by johann-petrak** [comment]
Fixed in version 0.6

**Comment by redtux** [comment]
I am using Ubuntu 19.10 and had to use `pip3 install licenseheaders`, so you might want to adjust the README accordingly. With `pip install licenseheaders` I get the following error:

> Could not find a version that satisfies the requirement licenseheaders (from versions: )
> No matching distribution found for licenseheaders

It is not obvious from the error message that this is related to a wrong python version. Personally, I would not have noticed without this bug report (which is why I am commenting here).

Thank you for your this awesome project!

**Comment by johann-petrak** [comment]
@redtux thanks, I updated the README file in an attempt to make this a bit clearer!

**Comment by redtux** [comment]
Great, thank you! 🎉 You might further want to replace -c by -o for the copyright owner. (At least the recent version does not have an option -c.)

**Comment by johann-petrak** [comment]
Thanks again!
