### ISSUE TITLE
adding license headers to scripts

### ISSUE THREAD

**Issue by tmbdev** [johann-petrak/licenseheaders#20]
Licenseheaders identifies files to modify based on their extension, but some files that need license headers don't have extensions.

I'd suggest adding an option that allows license headers to be added to such files:

```
    licenseheaders ...other options... --type py script1 script2 script3
```

Here, `--type` would use the extension to set the type for the explicit arguments.

**Comment by johann-petrak** [comment]
Could you explain better which files would be affected? I have never seen Python files with no extension and would not know why anyone would do this? 
This tool is mainly for those cases where you have a large number of files to process, updating the license headers for a few files manually is not that much of a problem normally. So if a solution for no extension files is needed because there are many such files, a different approach to specify them and their types may be preferable.

**Comment by johann-petrak** [comment]
No response, closing for now.
